language: python
python:
  - 2.7
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip

# Only run additional style checks with Python 3 dependencies on Python 3.
# (These conditionals are written weirdly backwards so that the command
# line evaluates to true.)

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - test "$TRAVIS_PYTHON_VERSION" != 3.6 || pip install -r requirements-dev3.txt
script: ci/test.sh
